import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, watch } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's GitHub repository
*/
`;

const __dirname = resolve(fileURLToPath(import.meta.url), '..');
const production = process.argv.includes('production');
const OBSIDIAN_PLUGIN_DIR = resolve(__dirname, '.obsidian', 'plugins', 'here-now-sync');

const getConfig = () => ({
  entryPoints: [resolve(__dirname, 'src/main.ts')],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  platform: 'node',
  outfile: resolve(__dirname, 'main.js'),
  sourcemap: production ? false : 'inline',
  minify: production,
  define: {
    'process.env.NODE_ENV': production ? '"production"' : '"development"'
  },
  logLevel: 'info'
});

const copyStylesToVault = () => {
  const src = resolve(__dirname, 'styles.css');
  const destDir = OBSIDIAN_PLUGIN_DIR;
  const dest = resolve(destDir, 'styles.css');

  if (!existsSync(src)) return console.warn("⚠️ styles.css is not in the project's root");
  if (!existsSync(destDir)) mkdirSync(destDir, { recursive: true });
  
  copyFileSync(src, dest);
  console.log('🎨 styles.css copied in Obsidian folder.');
};

if (production) {
  console.log('📦 Building production bundle...');
  esbuild.build(getConfig())
    .then(copyStylesToVault)
    .then(() => console.log('✅ Ready: main.js + styles.css'))
    .catch((err) => {
      console.error('❌ Build failed:', err);
      process.exit(1);
    });

} else {
  console.log('👀 Starting development watch mode...');

  esbuild.context(config).then(context => {
    context.watch();
    // Also watch styles.css for changes in dev mode
    watch(resolve(__dirname, 'styles.css'), copyStylesToVault);
    console.log('✨ Watching for changes. Press Ctrl+C to stop.');
  });
}
